### ISSUE TITLE
Add the ability to list more channels by the user

### ISSUE THREAD

**Issue by AhmedKamal20** [emad-elsaid/live#1]
### Add the ability to list more channels added by the user
But given that the app has no users or DB, and to refrain from using the cookies, the user can add more channels by putting it in the URL separated by a comma, for example: `https://live.emadelsaid.com?my_channels=UCNye-wNBqNL5ZzHSJj3l8Bg,UCNye-wNBqNL5ZzHSJj3l8Bg`

I know I can deploy my own version listing my favorite channels, but I find this way more convenient 

What do you think?

**Comment by AhmedKamal20** [comment]
I'm working on it ( First time GO!), I created the API Key but I exceeded the quota in the first couple of minutes ( 10,000 requests!!), I don't think I did all those request!

**Comment by emad-elsaid** [comment]
that doesn't seem right. the program make 1 request for each channel per program run then again every 1 hour.
this can happen if you restarted your application too many time it can exhaust the rate limit. to avoid that you can empty your channels.go array

**Comment by emad-elsaid** [comment]
as for the original idea it won't be valid because adding the channels to the URL means users of the application will directly use the quota of the youtube API. 
so I will stick to one list of channels in the whole program instance. 
the part of having users that favorite channels feels good. this means so many things
- a user identification (user login)
- a database to keep track of user favorites
- couple routes to favorite/unfavorite/list favorites

**Comment by emad-elsaid** [comment]
Search endpoint consumes 100 quota credit per request. and every project has 10,000 credit per day. 
so this means we can do total 100 requests per day. we have now 21 channels on the list so we can refresh them 4 times before we hit the quota.
I hate youtube API a wish there is another way. crawling the pages is very dirty method I hope I don't get to do that

**Comment by AhmedKamal20** [comment]
> Search endpoint consumes 100 quota credit per request. and every project has 10,000 credit per day.

Aha!, Wow, that sucks

> as for the original idea it won't be valid because adding the channels to the URL means users of the application will directly use the quota of the youtube API.

Yeah, I got you.

> crawling the pages is very dirty method I hope I don't get to do that

seems like it
We can try this solution : https://stackoverflow.com/a/68494021/4878911

**Comment by emad-elsaid** [comment]
that's actually a nice solution, it's all we need, and we don't need the API at all in this case. in that case we'll just need to reimplement the `liveVideos` function. and cleanup

**Comment by emad-elsaid** [comment]
actually after thinking about it all we need is for this function to return boolean instead and we can use the https://youtube.com/channel/id/live as the link, we don't need the video ID.
and the function can be used just to filter channels without live videos

**Comment by emad-elsaid** [comment]
I tried to implement the HTTP redirection method and failed. I see that YouTube did not issue HTTP redirect. instead it's loading the page as normal.
I believe that what is happening is that YouTube uses browser history JavaScript API to push a new path and play the live video.
I haven't checked the mobile version of YouTube it may behave differently
